name: build
permissions:
    contents: write

on:
    push:
        branches: [ "main" ]
        paths-ignore:
            - '**/README.md'

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 7.0.x
            - name: Get Version
              id: version
              uses: notiz-dev/github-action-json-property@release
              with:
                path: 'plugin.json'
                prop_path: 'Version'
            - run: echo ${{steps.version.outputs.prop}}
            - name: Restore
              run: |
                dotnet restore
            - name: Build
              run: |
                dotnet publish -c Release -r win-x64 --no-self-contained Flow.Launcher.Plugin.StardewValleyWiki.csproj
                7z a -tzip "Flow.Launcher.Plugin.StardewValleyWiki.zip" "./bin/Release/win-x64/publish/*"
            - name: Publish
              uses: softprops/action-gh-release@v2
              with:
                files: "Flow.Launcher.Plugin.StardewValleyWiki.zip"
                tag_name: "v${{steps.version.outputs.prop}}"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}